// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erbzkennjnczwjomcvld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYnprZW5uam5jendqb21jdmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDk5OTIsImV4cCI6MjA2MzgyNTk5Mn0.mnEQp99X8ehzrCP-f9zzUWWBec0BVbQYBezLfccz9Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);